### ISSUE TITLE
Pass open file to company logo option

### ISSUE THREAD

**Issue by schristm** [excid3/receipts#12]
Hey Chris,

It would be really awesome if you could pass an ActiveStorage attachment or other open stream/tempfile to the invoice's company logo. Is this a feature you'd consider implementing? Thanks!

**Comment by excid3** [comment]
According to the Prawn docs, that looks like it would be easy enough as long as you pass it an object that implements `read`

```ruby
  require "open-uri"

  Prawn::Document.generate("remote_images.pdf") do 
    image open("http://prawn.majesticseacreature.com/media/prawn_logo.png")
  end
```

Should be a pretty simple change.

**Comment by schristm** [comment]
Hey Chris,

Thanks for the reply. You're not saying this should work currently, though, right? I just tried updating my code to use `company: { logo: => account.logo.service_url }` and it just hangs. I tried `account.logo.download` as well. The only way I've managed to get this to work is like so:

```ruby
if account.logo.attached?
  account.logo.open do |file|
    receipt[:company][:logo] = file.path
    Receipts::Receipt.new(receipt).render
  end
else
  Receipts::Receipt.new(receipt).render
end
```

**Comment by excid3** [comment]
Yeah, it works for me if you `require "open-uri"` in your code before rendering the receipt.

We can probably update the lib to check if the `logo` argument responds to `read` so you can pass a file-like object in directly, otherwise it can assume it's a file path like we currently do. That way you can supply your own file object from anywhere (including in memory).

**Comment by schristm** [comment]
Hmm, I tried what you suggested, and I still can't get it to work. I tried passing `account.logo` by itself, and I get:

```
undefined method `empty?' for #<ActiveStorage::Attached::One:0x00007fa0d44d3a60>
```

If I try `account.logo.service_url` it just hangs forever/doesn't respond.

And, if I try `account.logo.download` it just kicks back this error: `path name contains null byte`.

I added `require "open-uri"` to the top of the file like you suggested as well.

**Comment by excid3** [comment]
The URL worked just fine for me when I passed in the GoRails logo's url. I'd make sure your URL actually works in the browser.

As for passing in an ActiveStorage attachment, that isn't a file object so you'd have to download it and pass the file object in once the library is updated to handle file types.

**Comment by excid3** [comment]
I just pushed a new version that lets you pass in a file object like we mentioned. Also included a `URI.open` example in the readme to show that.

**Comment by schristm** [comment]
So, the latest change introduced a bug:

```
undefined local variable or method `logo_path'
```

However, I can see that this change still isn't going to really make it any easier to pass an ActiveStorage attachment, unless I'm just completely missing something. `account.logo.service_url` does indeed return a URL that I can access via the browser, however I kept getting back `path name contains null byte` when I tried to use that approach before.

You can't pass a file pointer from ActiveStorage other than through the `open` method, which requires a block, and results in the redundant code I shared initially.

Even if you pass `account.logo.download`, it's going to just be a string with the attachment data loaded into memory.

So, I think the solution is to either fix whatever is causing the `path name contains null byte` issue when trying to pass an ActiveStorage url to the logo, or add allow passing an ActiveStorage object directly, and calling the download method if `object is_a? ActiveStorage::Attached`

**Comment by schristm** [comment]
Something like this:

```ruby
case logo
  when ActiveStorage::Attached
    image logo.download, height: 32
  when String
    image open(logo), height: 32
  else
    move_down 32
end
```

**Comment by excid3** [comment]
Ah yep, sorry. Just fixed that.

Without an example URL to replicate your issue, I can't help much there. open-uri works great from all the public image URLs I've tested, so it sounds like something on your end.

**Comment by schristm** [comment]
This is the value of `account.logo.service_url`:

```
http://slamdot.lvh.me:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhkakYwYzJrek1tUm5iWE14Ym1jME1teHFjVzlyZDJGbFptOXpaZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUVdsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1aaGRtbGpiMjR1Y0c1bklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZG1ZWFpwWTI5dUxuQnVad1k3QmxRNkVXTnZiblJsYm5SZmRIbHdaVWtpRG1sdFlXZGxMM0J1WndZN0JsUT0iLCJleHAiOiIyMDIwLTA3LTA1VDIzOjA4OjA5LjMyM1oiLCJwdXIiOiJibG9iX2tleSJ9fQ==--353811431c142fd3ac20fc9e987cf27f22897a7a/favicon.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22favicon.png%22%3B+filename%2A%3DUTF-8%27%27favicon.png
```

**Comment by excid3** [comment]
An lvh.me address isn't something I can test with since it's your localhost. Got something real I can use?

**Comment by schristm** [comment]
Yes, but that's the use case here - trying to use a local ActiveStorage attachment. An external URL may very well work just fine. A local ActiveStorage attachment using disk storage does not.

**Comment by schristm** [comment]
Now I'm getting this result (using `logo: account.logo.service_url`):

```
  Disk Storage (0.8ms) Generated URL for file at key: v1tsi32dgms1ng42ljqokwaefosf (http://slamdot.lvh.me:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhkakYwYzJrek1tUm5iWE14Ym1jME1teHFjVzlyZDJGbFptOXpaZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUVdsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1aaGRtbGpiMjR1Y0c1bklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZG1ZWFpwWTI5dUxuQnVad1k3QmxRNkVXTnZiblJsYm5SZmRIbHdaVWtpRG1sdFlXZGxMM0J1WndZN0JsUT0iLCJleHAiOiIyMDIwLTA3LTA1VDIzOjE1OjMxLjIwNloiLCJwdXIiOiJibG9iX2tleSJ9fQ==--e4c228d33aab452e0d6937b20ae6c1fd8eaa56bb/favicon.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22favicon.png%22%3B+filename%2A%3DUTF-8%27%27favicon.png)
Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhkakYwYzJrek1tUm5iWE14Ym1jME1teHFjVzlyZDJGbFptOXpaZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUVdsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1aaGRtbGpiMjR1Y0c1bklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZG1ZWFpwWTI5dUxuQnVad1k3QmxRNkVXTnZiblJsYm5SZmRIbHdaVWtpRG1sdFlXZGxMM0J1WndZN0JsUT0iLCJleHAiOiIyMDIwLTA3LTA1VDIzOjE1OjMxLjIwNloiLCJwdXIiOiJibG9iX2tleSJ9fQ==--e4c228d33aab452e0d6937b20ae6c1fd8eaa56bb/favicon.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22favicon.png%22%3B+filename%2A%3DUTF-8%27%27favicon.png" for 127.0.0.1 at 2020-07-05 19:10:31 -0400
Connection error: Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
Completed 406 Not Acceptable in 121539ms (ActiveRecord: 231.5ms | Allocations: 607604)
```

**Comment by excid3** [comment]
Well,ActiveStorage URLs are just redirects, not direct links to the file. You need to supply the direct file link for it to download or follow the redirect to it.

That feels out of scope for the receipts gem to care about. Files can be uploaded and stored a million different ways and I don’t want to be implementing exceptions for every one.

**Comment by schristm** [comment]
That's a fair point, but what about providing a parameter to pass the image data (such as from the `download` method) then?

**Comment by excid3** [comment]
That's what I did in the release I just made?

If it's a string, open the file. If not, assume it's a file.

https://github.com/excid3/receipts/blob/master/lib/receipts/receipt.rb#L53-L59

**Comment by schristm** [comment]
Because `download` also returns a string

**Comment by excid3** [comment]
Then wrap it in a StringIO. Prawn will not accept a string for an image, so you must pass in a file-like object like I mentioned.

**Comment by excid3** [comment]
I also confirmed that open-uri works just fine with local ActiveStorage URLs.

```
logo: URI.open('http://localhost:5000/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b200cddb6b870f428a1f18c7874cc32e5c7c6da7/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9VWTI5dFltbHVaVjl2Y0hScGIyNXpld2c2RG5Sb2RXMWlibUZwYkVraUN6UTRlRFE0WGdZNkJrVlVPZ3huY21GMmFYUjVTU0lMWTJWdWRHVnlCanNIVkRvTFpYaDBaVzUwU1NJS05EaDRORGdHT3dkVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--39d553421cb3ce81eea5a246e613c0cca31ef8c7/Screen%20Shot%202020-06-24%20at%209.13.38%20PM.png')
```

**Comment by schristm** [comment]
I'm just going to have to stick with the code I posted in the beginning, because neither of those suggestions worked for me.

This resulted in a gray screen / broken PDF.

```ruby
    if account.logo.attached?
      document[:company][:logo] = StringIO.new(account.logo.download)
    end
```

This resulted in the same timeout. Could be due to my URL having `.lvh.me` and yours being `localhost`.

```
    if account.logo.attached?
      document[:company][:logo] = URI.open(account.logo.service_url)
    end
```

Anyhow, thanks for trying to help.

**Comment by excid3** [comment]
Yeah, sounds like something on your end causing issues. Could be lvh.me, but I'm not sure. Definitely working fine for me with localhost.

**Comment by gathuku** [comment]
This works for me but at first was hanging
```
logo: URI.open(rails_representation_url(account.logo_image.variant(resize_to_limit: [200, 200]).processed, host: "http://localhost:3000"))
```
